# Generated by Django 3.2.14 on 2022-07-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.brand'),
        ),
    ]
