# Generated by Django 3.2.14 on 2022-07-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
