# Generated by Django 3.2.14 on 2022-07-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_product_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
