# Generated by Django 3.2.14 on 2022-08-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brochure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
